version: "3.3"

services:
  homeintent:
    build: .
    container_name: homeintent
    restart: unless-stopped
    volumes:
      - "./development-env/rhasspy:/profiles"
      - "./development-env/config:/config"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "12101:12101"
      - "11102:11102"
    devices:
      - "/dev/snd:/dev/snd"
    environment:
      - LANGUAGE=de

  marytts:    
    image: synesthesiam/marytts:5.2
    restart: "no"
    ports:
      - 59125:59125
    command: --voice bits1-hsmm --voice bits3-hsmm --voice dfki-pavoque-neutral-hsmm  
