RHASSPY_VERSION = "2.5.10"

BUILD_DOCS = """
FROM python:3.7
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /usr/src/app/docs

COPY docs/requirements.txt ./
RUN pip3 install --no-cache-dir -r requirements.txt

COPY docs .
RUN mkdocs build
"""

BUILD_FRONTEND = """
FROM node:lts
WORKDIR /usr/src/app/ui/frontend

COPY ui/frontend/package.json ui/frontend/package-lock.json ./
RUN npm ci

COPY ui/frontend .
RUN npm run build
"""


BUILD_VENV = """
FROM python:3.7
WORKDIR /usr/src/app

ENV LANG=C.UTF-8
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

ENV PATH="/venv/bin:$PATH"

RUN python -m venv /venv --copies
COPY requirements.txt ./
RUN pip3 install --no-cache-dir -r requirements.txt
"""


FINAL_BULD = """
FROM {BUILD_IMAGE}
WORKDIR /usr/src/app

ENV PYTHONUNBUFFERED=1
ENV PATH="/venv/bin:$PATH"

COPY {VENV_LOCATION} /venv
COPY {DOCS_LOCATION} ./docs/site
COPY setup setup
COPY home_intent home_intent
COPY ui ui
COPY {FRONTEND_LOCATION} ./ui/frontend/build

ENTRYPOINT {ENTRYPOINT}
"""

WARNING = """### NOTE: THIS FILE IS AUTOGENERATED FROM generate_dockerfiles.py ###"""


def main():
    make_local_dockerfile()
    make_gh_actions_dockerfiles()


def make_local_dockerfile():
    final_build = FINAL_BULD.format(
        BUILD_IMAGE=f"rhasspy/rhasspy:{RHASSPY_VERSION}",
        VENV_LOCATION="--from=1 /venv",
        DOCS_LOCATION="--from=0 /usr/src/app/docs/site",
        FRONTEND_LOCATION="--from=2 /usr/src/app/ui/frontend/build",
        ENTRYPOINT='[ "bash", "/usr/src/app/setup/setup.sh" ]',
    )

    dockerfile = f"""
{WARNING}

{BUILD_DOCS}

{BUILD_VENV}

{BUILD_FRONTEND}

{final_build}
"""


def make_gh_actions_dockerfiles():
    make_static_dockerfile()
    make_rhasspy_external_dockerfile()
    make_gh_build_dockerfile()


def make_static_dockerfile():
    dockerfile = f"""
{WARNING}

{BUILD_DOCS}

{BUILD_FRONTEND}

FROM scratch
COPY --from=0 /usr/src/app/docs/site /docs/site
COPY --from=1 /usr/src/app/ui/frontend/build /ui/frontend/build
"""

    print(dockerfile)


def make_rhasspy_external_dockerfile():
    final_build = FINAL_BULD.format(
        BUILD_IMAGE="python:3.7-slim",
        VENV_LOCATION="--from=0 /venv",
        DOCS_LOCATION="tmp/static/docs/site",
        FRONTEND_LOCATION="tmp/static/ui/frontend/build",
        ENTRYPOINT='[ "supervisord", "--configuration", "/usr/src/app/setup/supervisord.conf" ]',
    )

    dockerfile = f"""
{WARNING}

{BUILD_VENV}

{final_build}
"""


def make_gh_build_dockerfile():
    final_build = FINAL_BULD.format(
        BUILD_IMAGE=f"rhasspy/rhasspy:{RHASSPY_VERSION}",
        VENV_LOCATION="--from=0 /venv",
        DOCS_LOCATION="tmp/static/docs/site",
        FRONTEND_LOCATION="tmp/static/ui/frontend/build",
        ENTRYPOINT='[ "bash", "/usr/src/app/setup/setup.sh" ]',
    )

    dockerfile = f"""
{WARNING}

{BUILD_VENV}

{final_build}
"""


if __name__ == "__main__":
    main()
