[tool.black]
line-length = 100
target-version = ['py38']

[tool.isort]
# https://github.com/PyCQA/isort/wiki/isort-Settings
profile = "black"

# will group `import x` and `from x import` of the same module.
force_sort_within_sections = true

combine_as_imports = true

[tool.pylint.'MESSAGES CONTROL']
extension-pkg-whitelist = "pydantic"
max-line-length = 100
disable = "C0114, C0115, C0116, W0707, W1203, R1720"

[tool.pylint.MASTER]
jobs=2
init-hook='from pylint.config.find_default_config_files import find_default_config_files; from pathlib import Path; import sys; sys.path.append(str(Path(Path(list(find_default_config_files())[0]).parent)))'
